# Stage 1: Build
FROM maven:3.9.9-eclipse-temurin-21 AS BUILD
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Run
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

COPY --from=BUILD /app/target/*.jar app.jar

EXPOSE 8080

ENV JAVA_OPTS="-XX:+EnableDynamicAgentLoading"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]